language: java
jdk: oraclejdk8

install: true
script: ./ci/travis-script.sh

addons:
  sonarcloud:
    organization: "xfournet-github"

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
